### PR TITLE
fix docs (add latch, reverse)

### LINKED ISSUE #48: docs are broken
The new types `latch` introduced in https://github.com/unconed/mathbox/pull/32 has no entry in `src/docs/primitives.js`, which seems to have broken docs generation.

### PR DESCRIPTION
**Pull request by ChristopherChudzicki**
Resolves #48

### CODE REVIEW

File: src/docs/primitives.js [hunk 1]
```diff
@@ -55,6 +55,7 @@ export default {
     { expr: "function (emit, x, y, z, i, j, k, time, delta) { ... }" },
   ],
   scale: ["data", "Human-friendly divisions on an axis, subdivided as needed"],
+  latch: ["data", "Control expr/data updates when conditions change"],
```
Comment (ChristopherChudzicki) [inline src/docs/primitives.js:58]: This i took from the description in #32

File: src/docs/primitives.js [hunk 2]
```diff
@@ -89,6 +90,7 @@ export default {
   ],
   resample: ["operator", "Resample data to new dimensions with a shader"],
   repeat: ["operator", "Repeat data in one or more dimensions"],
+  reverse: ["operator", "Reverse data in one or more dimensions"],
```
Comment (ChristopherChudzicki) [inline src/docs/primitives.js:93]: #32 's changelog did not have an entry for reverse...This description is probably true? If vague?

Comment (sritchie) [reply src/docs/primitives.js:93]: Haha I was stymied as well when I looked at this yesterday. If it becomes clear while porting the examples I'll add to these.
